review_version: 3.0
bookname: syntax-book
language: ja
booktitle: {name: "Re:VIEW文法使用例", file-as: "リビューブンポウシヨウレイ"}
aut: [{name: "武藤健志", file-as: "ムトウケンシ"}]
date: 2018-10-16
history: [["2017-09-30", "2018-10-16"]]
debug: true
stylesheet: ["style.css"]
toclevel: 3
secnolevel: 4
coverimage: cover.jpg

# highlight:
#   html: "rouge"
#   latex: "listings"

opf_prefix: {ebpaj: "http://www.ebpaj.jp/"}
opf_meta: {"ebpaj:guide-version": "1.1.3"}

epubmaker:
  htmlext: xhtml

texstyle: ["reviewmacro"]
#texdocumentclass: ["review-jsbook", "cameraready=print,paper=b5"]
texdocumentclass: ["review-jsbook", "cameraready=ebook,paper=b5"]
#texdocumentclass: ["review-jsbook", "cameraready=print,paper=b5,bleed_margin=3mm,cover=true,Q=14,startpage=3,serial_pagination=true,hiddenfolio=nikko-pc"]
# texcommand: "uplatex"
# texoptions: null
# dvicommand: "dvipdfmx"
# dvioptions: "-d 5"

pdfmaker:
  toc: true
  colophon: true
  makeindex: true
  makeindex_dic: syntax.dic
  coverimage: cover-b5.ai
